# Generated by Django 4.0.2 on 2022-02-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
